- HelloWorld.java
> 2311502273 Cihan Eren Karpınar

- Evden Spora Gitme Algoritması.txt
- helloWorld.java
First week Hello World homework
> 2311502241 Arda Göktaş

- java giriş
> Create java giriş

- Homework_week1/irem özbey
> Create irem özbey

- Ayşe Çığrı Ödev
Çay demleme algoritması ve java dilinde java öğreniyorum yazan kod
> Create Ayşe Çığrı Ödev

- Homework_week1/Eslem Meydanlı
> Create Eslem Meydanlı

- Fatih Selim ADALI
> Create Fatih Selim ADALI

- Ceren Mutlu Ödev
> Create Ceren Mutlu Ödev

- meltemlikoglu odev
//bir sayinin iki basamakli oldugunu bulma algoritmasi
1-basla
2-sayi giriniz
3-eger sayi 9'dan buyuk ve 100'den kucukse 
4-yazdir sayi iki basamaklidir
5-eger sayi 9'dan kucuk esit veya 100'den buyuk esitse
6-yazdir sayi iki basamakli degildir
7-bitir
//java 
public class Main {
System.out.println("merhaba javayi ogreniyorum.");
}
}
> Create meltemlikoglu odev

- Homework_week1/elifnurbeycan ödev
girilen sayinin tek mi cift mi oldugunu bulan algoritma ve merhaba ben java ögreniyorum yazan java kodu
// Girilen sayinin tek mi çift mi oldugunu bulan algoritma
1-Başla
2-Sayi giriniz
3-a=sayi%2
4-a 0'a esit ise ekrana yazdır 'girdigin sayi çift'
5-a 0'a esit değil ise ekrana yazdır 'girdigin sayi tek'
6-Bitir
//javada 'merhaba  ben java ogreniyorum' yazan kod
public class Main {
System.out.printf("merhaba ben java ogreniyorum");
}
}
> Create elifnurbeycan ödev

- Homework_week1/Main.java
- Homework_week3/Ops.java
> Onur Mustafa Uzman

- Homework_week3/mevliye balandi
>  mevliye balandi

- Homework_week3/meltem likoğlu isimsoyisim
> Create meltem likoğlu

- Homework_week3/Gaye Nur Güneş
> Create Gaye Nur Güneş

- Homework_week3/özgesanal.java
> özgesanal.java

- Homework_week3/MuhammedNebiAltinVirguldenSonrakiDeger.java
MuhammedNebiAltin_2311502278_OdevHafta3
> MuhammedNebiAltin_2311502278_OdevHafta3

- Homework_week3/Main.java
- Homework_week3/Main2.java
Your lectures are inspired me a lot. Thank you for your passion in teaching. You are paving the way for us to become like you in the future. I will try to do whatever I could to learn OOP with your assistance. :)
> NİSANUR GÜRSES 2311502258

- Homework_week3/Ceren Mutlu
> Create Ceren Mutlu

- kader güneş
> Create kader güneş

- Homework_week4/mevliye balandı
girilen sayıya kadar for döngüsüyle ekrana yazdırma
> Create mevliye balandı

- Homework_week4/Ceren Mutlu sayıları yazdırma
100'den girilen sayıya kadar olan sayıları ekrana yazdırma
> Create Ceren Mutlu sayıları yazdırma

- Homework_week1/algoritma_MevliyeBalandi
pankek tarifinin pseudo kod ile yazımı
> algoritma_MevliyeBalandi

- Homework_week4/mecliye balandi yashesaplama
yas hesaplama 
mevliye balandi
>  mevliye balandi yashesaplama

- Homework_week4/PrintNumberWithForSumeyyeElgin.java
kullanıcıdan sayı alınarak 1'e kadar yazdıran, kullanıcının 100'den küçük bir sayı girmesi durumunda do while döngüsüyle kullanıcıdan tekrar sayı girmesini isteyen, derste yaptığımız pratik
> sümeyye elgin 2311502275

- Homework_week4/elif nur beycan
girilen sayıdan geriye yazdırma
> Create elif nur beycan

- Homework_week4/Mertcan Çelik
> Create Mertcan Çelik

- Homework_week4/not ortalaması-mevliye
not ortalamsına göre geçti kaldı söyleme
>  not ortalaması-mevliye

- Homework_week4/Ceren Mutlu ay hesaplama
> Create Ceren Mutlu mevsim hesaplama

- Homework_week4/Ceren Mutlu ortalama hesaplama
> Create Ceren Mutlu ortalama hesaplama

- Homework_week4/meltem likoglu aylar
> Create meltem likoglu aylar

- Homework_week4/Ceren Mutlu yaş hesaplama
> Create Ceren Mutlu yaş hesaplama

- Homework_week4/AgesArda.java
- Homework_week4/GPAArda.java
- Homework_week4/MonthsArda.java
- Homework_week4/NumPrinter.java
I hope the conflict issue is solved.
> Arda Göktaş Week4

- Homework_week6/mevliye balandi
> mevliye balandi 2311502204

- Homework_week6/GurhanK_KisiBilgi/GurhanK_KisiBilgi.java
- Homework_week6/GurhanK_KisiBilgi/KisiBilgi_Execute.java
- Homework_week6/GurhanK_Variable/GurhanK_VariableExample.java
- Homework_week6/GurhanK_Variable/Main.java
Variable Dosyası ve Kişi bilgilerinin tanımlandığı dosyalar
> GurhanK_OOP6.1

- Homework_week6/2311502206 Ahmet Kaan Başkan hafta 6
package week6;
public class AhmetKaanBaskanMyClass {
public String name;
public String surname;
public int age;
public String uni;
public String major;
public String hairColor;
public float height;
public boolean isBeard;
public boolean isMoustache;
public String hobby;
AhmetKaanBaskanMyClass kaan = new AhmetKaanBaskanMyClass();
kaan.name = "ahmet kaan";
kaan.surname = "BASKAN";
kaan.age = 2024 - 2004;
kaan.uni = "Bandirma 17 Eylül Üniversite";
kaan.major = "bilgisayar mühendisliği";
kaan.hairColor = "siyah";
kaan.height = 1.89F;
kaan.isBeard = true;
kaan.isMoustache = true;
kaan.hobby = "kod yazmak";
System.out.println("isim: " + kaan.name);
System.out.println("soy isim: " + kaan.surname);
System.out.println("yaş: " + kaan.age); …
> Create 2311502206 Ahmet Kaan Başkan hafta 6

- Homework_week6/Nisanur Goren
- Homework_week6/NisanurGoren
[Java Odev.txt](https://github.com/themanoftalent/JavaBasics_OOP/files/14852485/Java.Odev.txt)
> Nisanur Goren 2311502215

- HomeWork/Homework_week2/Gaye Nur Güneş
Homework 3 ve 4 dosyalarına ekleme yapamadığım için(There was an error committing your changes: File could not be edited hatası veriyor) ödev dosyalarımın hepsini homework2 dosyası içine ekliyorum...
> Gaye Nur Güneş

- Hafta1 ödev
> Create Hafta1 ödev

- HomeWork/Homework_week1/Adem memis Assignment2.java
> Adem memis Assignment2.java

- HomeWork/Homework_week2/EmreYilmazHomework6PalindromeCheckk.java
- HomeWork/Homework_week4/EmreYilmazHomework10ReverseaStringg.java
> Emre Yılmaz 2311502246

- HomeWork_week2 Assigment(4,5,6).java
//Segbe Abdoul Aziz Diomande 2311502290
//Assigment4
//Segbe Abdoul Aziz Diomande
import java.util.Scanner;
public class Assigment4 {
Scanner scanner = new Scanner(System.in);
System.out.print("Enter the number : ");
int number = scanner.nextInt();
long factorial = 1;
for (int i = 1; i <= number; i++) {
factorial *= i;
}
System.out.println("The factorial is " + number + " is : " + factorial);
}
}
//Assigment5
import java.util.Scanner;
public class Assigment5 {
Scanner scanner = new Scanner(System.in);
System.out.print("Enter the number of terms of the Fibonacci sequence to generate : ");
int numberTerms = scanner.nextInt();
int firstTerms = 0;
int secondTerms = 1;
System.out.print("Fibonacci sequence up " + …
> segbe abdoul aziz 2311502290 Assigment(4,5,6).java

- segbe abdoul aziz 2311502290 Assigment(7,8,9).java
//Segbe Abdoul Aziz Diomande
//Assigment7
import java.util.Scanner;
public class Assigment7 {
Scanner scanner = new Scanner(System.in);
System.out.print("Enter a positive integer: ");
int number = scanner.nextInt();
int sum = sumOfDigits(number);
System.out.println("The sum of digits of " + number + " is: " + sum);
}
public static int sumOfDigits(int number) {
int sum = 0;
while (number != 0) {
sum += number % 10;
number /= 10;
}
return sum;
}
}
//Assigment8
import  java.util.Scanner;
public class Assigment8 {
Scanner scanner = new Scanner(System.in);
System.out.print("Enter a number: ");
int number = scanner.nextInt();
System.out.println("Multiplication table of " + number + ":");
for (int i = 1; i <= 10; …
> Create segbe abdoul aziz 2311502290 Assigment(7,8,9).java

- HomeWork/Homework_week1/Onur_M_U_Homework1helloWorld.java
- HomeWork/Homework_week1/Onur_M_U_Homework2SimpleCalculator.java
- HomeWork/Homework_week1/Onur_M_U_Homework3EvenorOdd.java
- HomeWork/Homework_week2/Onur_M_U_Homework4FactorialCalculator.java
- HomeWork/Homework_week2/Onur_M_U_Homework5FibonacciSequence.java
- HomeWork/Homework_week2/Onur_M_U_Homework6PalindromeCheck.java
- HomeWork/Homework_week3/Onur_M_U_Homework7SumOfDigits.java
- HomeWork/Homework_week3/Onur_M_U_Homework8MultiplicationTable.java
- HomeWork/Homework_week3/Onur_M_U_Homework9PrimeNumberChecker.java
- HomeWork/Homework_week4/Onur_M_U_Homework10ReverseaString.java
- HomeWork/Homework_week4/Onur_M_U_Homework11ArraySumandAverage.java
- HomeWork/Homework_week4/Onur_M_U_Homework12ArraySorting.java
- HomeWork/Homework_week5/Onur_M_U_Homework13LinearSearch.java
- HomeWork/Homework_week5/Onur_M_U_Homework15MatrixOperations.java
- HomeWork/Homework_week6/Onur_M_U_Homework16ArmstrongNumber.java
- HomeWork/Homework_week6/Onur_M_U_Homework17FileReadWrite.java
- HomeWork/Homework_week6/Onur_M_U_Homework18ExceptionHandlingExample.java
> OnurMustafaUzman

- HomeWork/Homework_week5/Muhammed_Nebi_Altın_Assignment13.java
- HomeWork/Homework_week5/Muhammed_Nebi_Altın_Assignment15.java
- HomeWork/Homework_week6/Muhammed_Nebi_Altın_Assignment16.java
- HomeWork/Homework_week6/Muhammed_Nebi_Altın_Assignment17.java
- HomeWork/Homework_week6/Muhammed_Nebi_Altın_Assignment18.java
> Muhammed_Nebi_Altın_Assignments(13,15)

- HomeWork/Homework_week1/helloWorld.java
- HomeWork/Homework_week1/hesapMakinesi.java
- HomeWork/Homework_week1/tekCift.java
- HomeWork/Homework_week2/faktoriyel.java
- HomeWork/Homework_week2/fibonacci.java
- HomeWork/Homework_week2/palindrom.java
- HomeWork/Homework_week3/asalSayi.java
- HomeWork/Homework_week3/carpimTablosu.java
- HomeWork/Homework_week3/rakamTopla.java
- HomeWork/Homework_week4/diziSırala.java
- HomeWork/Homework_week4/diziTopOrt.java
- HomeWork/Homework_week4/dogrusalArama.java
- HomeWork/Homework_week4/ikiliArama.java
- HomeWork/Homework_week4/matrisIslem.java
- HomeWork/Homework_week4/tersCevir.java
- HomeWork/Homework_week5/dogrusalArama.java
- HomeWork/Homework_week5/ikiliArama.java
- HomeWork/Homework_week5/matrisIslem.java
- HomeWork/Homework_week6/armstrongSayi.java
- HomeWork/Homework_week6/dosyaOkuYaz.java
- HomeWork/Homework_week6/istisna.java
> Emiralp Yakalı 2311502251

- HomeWork/Homework_week4/Adem memis Assignment11.java
> Adem memis Assignment11.java

- HomeWork/Homework_week1/Homework  3 Ismayil 2311502298
>  Homework  1 Ismayil 2311502298

- HomeWork/Homework_week1/Homework Fuad Alakbarli 23115502201
> Create Homework Fuad Alakbarli 23115502201

- HomeWork/Homework_week2/Home werk Ismayil Maharramli
>  Home werk 4,5,6  Ismayil Maharramli

- HomeWork/Homework_week1/Hm wk 1,2,3 Ismayil.Mh
> Create Hm wk 1,2,3 Ismayil.Mh

- HomeWork/Homework_week3/Hm Wk 7,8,9 Ismayil Maharramli
> Create Hm Wk 7,8,9 Ismayil Maharramli

- HomeWork/Homework_week4/Homework 10,11,12 Fuad Alakbarli
//2311502201
Homework 10,11,12
> Create Homework 10,11,12 Fuad Alakbarli

- HomeWork/Homework_week6/Hm Wk 16,17,18 Ismayil Maharramli
> Create Hm Wk 16,17,18 Ismayil Maharramli

- HomeWork/Homework_week6/Home work 16,17,18 Fuad Alakbarli
> Create Home work 16,17,18 Fuad Alakbarli

- HomeWork/Homework_week1/Homework 1,2,3 Aladdin Rasulzade
> Create Homework 1,2,3 Aladdin Rasulzade

- HomeWork/home work 4,5,6 Aladdin Rasulzade
> Create home work 4,5,6 Aladdin Rasulzade

- HomeWork/Homework_week3/Home work 7,8,9 Aladdin Rasulzade
> Create Home work 7,8,9 Aladdin Rasulzade

- HomeWork/Homework_week4/Home work 10,11,12 Aladdin Rasulzade
> Create Home work 10,11,12 Aladdin Rasulzade

- HomeWork/Homework_week5/Home work 13,15 Aladdin Rasulzade
> Create Home work 13,15 Aladdin Rasulzade

- HomeWork/Homework_week6/Home work 16,17,18 Aladdin Rasulzade
> Create Home work 16,17,18 Aladdin Rasulzade

- HomeWork/Homework_week1/cedric diffo segnou 2311502294
> Create cedric diffo segnou 2311502294
